-- MySQL Script generated by MySQL Workbench
-- Mon Aug 22 21:06:46 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FarmaBonos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema FarmaBonos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FarmaBonos` DEFAULT CHARACTER SET utf8 ;
USE `FarmaBonos` ;

-- -----------------------------------------------------
-- Table `FarmaBonos`.`Ubicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FarmaBonos`.`Ubicacion` (
  `IDUbicacion` INT NOT NULL,
  `Ubicacion` VARCHAR(45) NULL,
  PRIMARY KEY (`IDUbicacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FarmaBonos`.`Medicamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FarmaBonos`.`Medicamentos` (
  `CodMedicamentos` VARCHAR(45) NOT NULL,
  `Medicamento` VARCHAR(45) NULL,
  `NomMolecular` VARCHAR(45) NULL,
  `Precio` DOUBLE NULL,
  `Cantidad` INT NULL,
  `CodProveedor` INT NOT NULL,
  `IDUbicacion` INT NOT NULL,
  PRIMARY KEY (`CodMedicamentos`, `CodProveedor`, `IDUbicacion`),
  INDEX `fk_Medicamentos_Ubicacion1_idx` (`IDUbicacion` ASC) VISIBLE,
  CONSTRAINT `fk_Medicamentos_Ubicacion1`
    FOREIGN KEY (`IDUbicacion`)
    REFERENCES `FarmaBonos`.`Ubicacion` (`IDUbicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FarmaBonos`.`Proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FarmaBonos`.`Proveedores` (
  `CodProveedor` INT NOT NULL,
  `NombreProveedores` VARCHAR(45) NULL,
  PRIMARY KEY (`CodProveedor`),
  CONSTRAINT `fk_Proveedores_Medicamentos`
    FOREIGN KEY (`CodProveedor`)
    REFERENCES `FarmaBonos`.`Medicamentos` (`CodProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
